openapi: 3.0.0  
info:
  title: Simple API overview
  version: 2.0.0
servers:
  - url: http://localhost:5000
    description: Test server
  - url: http://waterfall.wwyf.top
    description: Production server
paths:
  # /apis:
  # /apis/user:
  # /apis/user/login:
  # /apis/user/register:
  # /apis/user/logout:
  # /apis/user/{userId}:
  # /apis/order/mainOrder/{mainOrderId}:
  # /apis/order/mainOrder/finish:
  # /apis/order/mainOrder/cancel:
  # /apis/order/subOrder
  # /apis/order/subOrder/{subOrderId}:
  # /apis/order/subOrder/finish:
  # /apis/order/subOrder/cancel:
  # /apis/wallet/{userId}:
  # /apis/wallet/deposit:
  # /apis/wallet/withdraw:
  /apis/order/mainOrder:
    get:
      summary: 获取所有主订单
      parameters:
        - name : limit
          description: 获取前limit个订单，如果不传入limit则limit默认为10，limit为-1代表获取所有订单
          in : query
          schema:
            type : integer
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                  data:
                    type: object
                    properties:
                      orders:
                        type: array
                        items:
                          type: object
                          properties:
                            mainOrderId:
                              type: string
                              description: 母订单id
                            order_name:
                              type: string
                              description: 订单姓名
                            create_date:
                              type: string
                              format: datetime
                              description: 订单创建日期
                              example: "2018-01-02"
                            order_ddl:
                              type: string
                              description: 订单截止日期
                              example: "2018-01-09"
                            quantity:
                              title: 订单货物数量
                              type: integer
                              example : 3
                            price:
                              title: 单件货物价格
                              type: integer
                              example : 534
                            total_price:
                              title: 订单总价格
                              type: integer
                              example: "243423"
                            userID:
                              title: 下达该订单的用户id
                              type: integer
                              format: int64
                            order_status:
                              title: 订单状态(TODO)
                              type: integer
                              enum:
                                - 0
                                - 1
                                - 2
                            order_progress:
                              title: 订单进度
                              type: integer
                              maximum: 100
                              minimum   : 0
                          
    post:
      summary: 提交新母订单
      requestBody:
        content:
          application/json:
            schema:
              properties:
                order_name: 
                  description: 订单名称
                  type: string
                  example: 鲜天下实例订单名称
                order_summary :
                  description: 订单概述
                  type: string
                  example: 鲜天下示例订单概述
                order_ddl:
                  description : 订单截止日期
                  type: string
                  format: datatime
                  example: "2019-02-05"
                address:
                  description: 订单收货地址
                  type: string
                  example: "广州市广州大学城外环东路132号"
                quantity :
                  description: 货物数量
                  type: integer
                  example: 50
                price :
                  description: 订单单价
                  type: integer
                  example: 100
                comments :
                  description: 订单备注
                  type: string
                  example: 空备注
                phone :
                  description: 联系方式
                  type: string
                  example: 13538383838
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    description: 错误码，0为正常
                    example: 0
                  data:
                    type: object
                    properties:
                      msg:
                        type: string
                        example: "已提交成功"
                      id:
                        type: integer
                        example: 89238

                  
components:
  schemas:
    Users:
      type: object
      properties:
        ID:
          title : 在数据库中用户的唯一ID
          type: integer
          format : int64
        username:
          title : 用户名
          type: string
        password:
          title : 哈希后的用户密码
          type: string
        email:
          title: 用户电子邮箱
          type: string
          default: null
        phone:
          title: 用户手机号码
          type: string
        balance:
          title: 用户余额
          type: integer
          format: int64
          default: 0
        usertype:
          title: 用户类型（0为管理员，1为订购商，2为微供应商）
          type: integer
          enum:
            - 0
            - 1
            - 2
    Orders:
      type: object
      properties:
        ID:
          title : 在数据库中订单的唯一ID
          type: integer
          format : int64
        name:
          title: 订单名称
          type: string
        createdate:
          title: 订单创建日期时间
          type: string
          format: datetime
        deadline:
          title: 订单截止时间
          type: string
          format: datetime
        address:
          title: 订单收获地址
          type: string
        amount:
          title: 订单货物数量
          type: integer
        price:
          title: 单件货物数量
          type: integer
        totalprice:
          title: 订单总价格
          type: integer
        createuser:
          title: 下达该订单的用户id
          type: integer
          format: int64
        comments:
          title: 订单备注
          type: string
        contect:
          title: 联系方式（即手机号码）
          type: string
        status:
          title: 订单状态(TODO)
          type: integer
          enum:
            - 0
            - 1
            - 2
        progress:
          title: 订单进度
          type: integer
          maximum: 100
          minimum   : 0
    subOrders:
      properties:
        ID:
          title : 在数据库中子订单的唯一ID
          type: integer
          format : int64
        createdate:
          title: 订单创建日期时间
          type: string
          format: datetime
        supplier:
          title: 该子订单供应商的id
          type: string
        amount:
          title: 订单货物数量
          type: integer
        price:
          title: 单件货物数量
          type: integer
        totalprice:
          title: 订单总价格
          type: integer
        comments:
          title: 订单备注
          type: string
        contect:
          title: 联系方式（即手机号码）
          type: string
        status:
          title: 订单状态(TODO)
          type: integer
          enum:
            - 0
            - 1
            - 2
        
  parameters:
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      required: true
      schema:
        type: integer
        format: int32
    limitParam:
      name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            title: Sample
            type: object
            properties:
              test1:
                type: string
                description: test1 description
              test2:
                type: integer
                description: test2 description
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    petstore_auth:
      type: oauth2
      flows: 
        implicit:
          authorizationUrl: http://example.org/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
                
